spring:
  application:
    name: condition_checker

open-weather-api:
  baseUrl: "https://api.openweathermap.org/data/3.0/onecall"
  endpoint: "/timemachine?lat=53.39293&lon=-2.98532&dt=%s&appid=%s&units=imperial"
  key: ${OPENWEATHER_API_KEY}

boats:
  feelsLikeTempMinCelsius: 0
  feelsLikeTempMaxCelsius: 27
  unacceptableIds: "2xx,302,312,314,5xx,6xx,7xx" #NO SPACES
  exceptionsToTheAbove: "500,501,520,600,601,612,615,616,620" #NO SPACES
  boatTypes:
    single:
      wind: 12
    double:
      wind: 13
    eight:
      wind: 17
    quads:
      wind: 14
#    the above are to be refined
# the above wind values are treated as the max allowed atm

wiremock:
  host: ${WIREMOCK_HOST:localhost}
  port: ${WIREMOCK_PORT:5050}

